POST http://localhost:3000/register
content-type: application/json
{
    "id" : 1,
    "title": "Sample title",
    "content": "Sample Content",
    "published": false
}

###
GET  http://localhost:3000/materials
###
PUT http://localhost:3000/update/
{
    "title": "Updated title",
}
###
DELETE http://localhost:3000/delete/
###