POST http://localhost:3000/register
content-type: application/json
{
    "title": "Sample title",
    "content": "Sample Content",
}

###
GET  http://localhost:3000/materials
###
PUT http://localhost:3000/update/
{
    "title": "Updated title",
    "published": true
}
###
DELETE http://localhost:3000/delete/
###